### ISSUE TITLE
Impossible to set Custom User Id before initializing

### ISSUE THREAD

**Issue by GrimLothar** [GameAnalytics/GA-SDK-UNITY#37]
Hey, looking at the [documentation](https://docs.gameanalytics.com/integrations/sdk/unity#custom-user-id), I see that Custom User ID needs to be set BEFORE initializing and at the start of the app lifetime
<img width="758" alt="Screenshot 2024-08-28 at 1 21 32 PM" src="https://github.com/user-attachments/assets/8a539dab-2b08-4c1f-9f4e-94ebf5575621">

This is practically impossible since the custom user id is only created after the user has been created on the login/registration section.

So is this really the case and documenation is wrong, or how can we solve this problem?

**Comment by dorin-ga** [comment]
The user id is required for GA's internal use, thus cannot be changed after the SDK has been initialized.

However, we have a special id created for cases like this called `external user id`. It is not internally used the GA SDK, this id can be changed anytime and will be attached to every event if present.

`
GameAnalytics.SetExternalUserId("my_external_user_id");
`

https://github.com/GameAnalytics/GA-SDK-UNITY/blob/c2a8ffab4edd668d98d23e696f9396e165bbb9e1/Runtime/Scripts/GameAnalytics.cs#L905

**Comment by GrimLothar** [comment]
Perfect! thank you

**Comment by GrimLothar** [comment]
> The user id is required for GA's internal use, thus cannot be changed after the SDK has been initialized.
> 
> However, we have a special id created for cases like this called `external user id`. It is not internally used the GA SDK, this id can be changed anytime and will be attached to every event if present.
> 
> `GameAnalytics.SetExternalUserId("my_external_user_id");`
> 
> https://github.com/GameAnalytics/GA-SDK-UNITY/blob/c2a8ffab4edd668d98d23e696f9396e165bbb9e1/Runtime/Scripts/GameAnalytics.cs#L905

Hey @dorin-ga , one question though... if I don't care about analytics before the user logs in (they do it pretty early in the game), would it make sense to just wait until they login in for initializing? Are there any downsides to this? What are the benefits of using user id vs external user id?

**Comment by dorin-ga** [comment]
That is also a valid option. There are several differences between user id and external user id that may influence your decision in using one over another. They are distinct identifiers and aren't a replacement for each other. 

The normal user id is a mandatory identifier, that is also used internally by GA to identify an unique player and will be used to detect new and existing players. Due to its nature it needs to be assigned when the SDK initializes. If no custom id is provided, the GA SDK will generate a random one. 

The external user id is an optional identifier, it's a custom identifier left at the discretion of the developer. It is not used internally by GA in calculating any metric. Use cases could be tracking events before users log-in then assigning it to their account name or when switching accounts. Can be set or changed at anytime.
